### ISSUE TITLE
mr.developer: The package 'slc.ipythonprofiles' is dirty.

### ISSUE THREAD

**Issue by pgrunewald** [syslabcom/slc.ipythonprofiles#1]
At first, let me say good job! It works like charm once it's installed, however I get the following message from mr.developer, when doing a second buildout after installing this add-on:

```
The package 'slc.ipythonprofiles' is dirty.
```

This is cumbersome, when creating a streamlined buildout process (where no interactive questions should appear).

Upon inspecting the repository, I get the following result:

```
$ git status
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        profile_zope/history.sqlite
        profile_zope/startup/
```

I guess those files need to be added to `.gitignore`?

**Comment by reinhardt** [comment]
Thanks, that makes sense! I've added a .gitignore file. Does that solve the issue?

**Comment by pgrunewald** [comment]
It does! Thanks a lot!
